# arxivの学問領域の指定
subject: 'cat:physics.* OR cat:math.* OR cat:nlin.* OR cat:stat.* OR cat:eess.* OR cat:cs.*'

# 検索キーワード
keywords:
        nuclear fusion: 10
        simulation: 3
        disruption: 3
        vacuum vessel: 3
        field line tracing: 3
        "ITER ": 5
        JT-60SA: 5
        "DEMO ": 5
        plasma: 5
        tokamak: 5
        eddy current: 5
        MHD equilibrium: 5
        Resonant Magnetic Perturbation: 5
        Resistive Wall Mode: 5
        VMEC: 10
        adjoint method: 5
        reinforcement learning: 5
        surrogate model: 5
        metaverse: 3
        virtual reality: 3
        augmented reality: 3
        merged reality: 3
        magnetic: 3
        

# 通知の閾値
score_threshold: 10

iop_rss_url:
 - https://iopscience-iop-org.kyoto-u.idm.oclc.org/journal/rss/0741-3335 # Plasma Physics and Controlled Fusion
 - https://iopscience-iop-org.kyoto-u.idm.oclc.org/journal/rss/0029-5515 # Nuclear Fusion
 - https://iopscience-iop-org.kyoto-u.idm.oclc.org/journal/rss/0963-0252 # Plasma Sources Science and Technology

elsevier_rss_url:
 - https://rss.sciencedirect.com/publication/science/00104655 # Computer Physics Communications
 - https://rss.sciencedirect.com/publication/science/00223115 # Journal of Nuclear Materials
 - https://rss.sciencedirect.com/publication/science/09270256 # Computational Materials Science
 - https://rss.sciencedirect.com/publication/science/23521791 # Nuclear Materials and Energy
 - https://rss.sciencedirect.com/publication/science/27728285 # Fundamental Plasma Physics
 - https://rss.sciencedirect.com/publication/science/09203796 # Fusion Engineering and Design
 - https://rss.sciencedirect.com/publication/science/05779073 # Chinese Journal of Physics
 - https://rss.sciencedirect.com/publication/science/01491970 # Progress in Nuclear Energy
 - https://rss.sciencedirect.com/publication/science/07437315 # Journal of Parallel and Distributed Computing
